apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  selector:
    matchLabels:
      app: department-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
        - name: department-service-app
          image: ttmunyunguma/department-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9001

---

kind: Service
apiVersion: v1
metadata:
  name: department-service-svc
spec:
  selector:
    app: department-service-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9001
