apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  selector:
    matchLabels:
      app: cloud-config-server-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
        - name: cloud-config-server-app
          image: ttmunyunguma/cloud-config-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9196

---

kind: Service
apiVersion: v1
metadata:
  name: cloud-config-server-svc
spec:
  selector:
    app: cloud-config-server-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9196
