apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
  labels:
    app: cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: cloud-gateway-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - name: cloud-gateway-app
          image: ttmunyunguma/cloud-gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8989

---

kind: Service
apiVersion: v1
metadata:
  name: cloud-gateway-svc
spec:
  selector:
    app: cloud-gateway-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8989
      protocol: TCP
